# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(default='151204', max_length=120),
        ),
    ]
