# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-04 23:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message="Username must be alphanumeric or contains:'. @ + -'", regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
